swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <svg></p><style><a id="</style><img src=//example.com onerror=alert(1)>">

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <svg></p><style><a id="</style><img src=1 onerror=alert(1)>">

          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteGroupById
      summary: Deletes a group by id
