swagger: '2.0'
info:
  version: "0.0.1"
  title: DVA Test
  description: <a title="<img src='#' onerror='alert(window.origin)'>">
paths:
  /:
    get:
      responses:
        200:
          description: Successful DVA response
