swagger: '2.0'
info:
  version: "0.0.1"
  title: DVA Test
  description: <img src=x onerror="alert('DVA')">
paths:
  /:
    get:
      responses:
        200:
          description: Successful DVA response
